name: Import TML to Org

on: 
  workflow_dispatch:
    inputs:
      TS_ORG_NAME:
        type: string
        description: 'ThoughtSpot org name (not org_id)'
        required: true
        default: 'Primary'
      OBJECT_TYPE:
        type: choice
        description: Type of Objects to Download
        options: 
        - ALL
        - LIVEBOARD
        - ANSWER
        - DATA
        required: true

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install thoughtspot_rest_api_v1 
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test Commit and push files
      env:
       TS_SERVER: ${{ secrets.TS_SERVER }}
       TS_SECRET_KEY: ${{ secrets.TS_SECRET_KEY }}
       TS_USERNAME: ${{ secrets.TS_USERNAME }}
       TS_ORG_NAME: ${{ github.event.inputs.TS_ORG_NAME }}
       OBJECT_TYPE: ${{ github.event.inputs.OBJECT_TYPE }}
 
      run: |
        git config --local user.email "bryant.howell@thoughtspot.com"
        git config --local user.name "bryanthowell-ts"
        python .github/workflows/import_tml_to_org.py > latest_import_run.log